config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # root to: "home#index"

  # Defines the root path route ("/")
  root to: "pages#splash"

  # Define routes for the users
  authenticate :user do
      root to:'groups#index', as: :authenticated_root
  end

  resources :groups do
    resources :specifications
  end
  # Define routes for the home page
  # root "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #

    user ||= User.new # guest user (not logged in)

    can :read, :pages, name: 'splash'

    # return unless user.persisted?

    # can :manage, :all

    if user.persisted? # logged in
      can :manage, :all, user_id: user.id
    else
      can :read, :pages, name: 'splash' # allow access to splash page for unauthenticated users
    end
    # if user.persisted? # logged in
    #   can :manage, Group, user_id: user.id
    #   can :manage, Specification, user_id: user.id
    #   can :manage, User, id: user.id
    # No abilities for guest users (not logged in)
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :specifications

  validates :name, presence: true
  validates :icon, presence: true

  def total_spent
    specifications.sum(:amount)
  end
end

app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true,
                     numericality: { only_float: true, greater_than_or_equal_to: 0.00,
                                     message: 'Please enter a valid amount' }

  validates :groups, presence: true, length: { minimum: 1, message: 'Please select at least one group' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :groups
  has_many :specifications, foreign_key: 'author_id'

  validates :name, presence: true, length: { minimum: 2, maximum: 45, message: 'must be between 2 and 20 characters' }
  validates :email, presence: true, length: { maximum: 255, message: 'must be less than 255 characters' }
  validates :password, presence: true,
                       length: { minimum: 6, maximum: 20, message: 'must be between 6 and 20 characters' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:splash]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :null_session

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Group.all.where(user_id: current_user.id).includes(:specifications)
  end

  def new
    @categorie = Group.new
  end

  def create
    @categorie = Group.new(group_params)
    @categorie.user_id = current_user.id
    if @categorie.save
      redirect_to groups_path, notice: 'Category was successfully created'
    else
      render 'new'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash; end
end

app/controllers/specifications_controller.rb
class SpecificationsController < ApplicationController
  def index
    @group = Group.find_by(user: current_user, id: params[:group_id])
    @specifications = @group.specifications
  end

  def new
    @specification = current_user.specifications.build
    @groups = current_user.groups
  end

  def create
    @specification = current_user.specifications.build(specification_params)
    @groups = params[:groups]
    @groups.each do |id|
      group = current_user.groups.find(id) unless id == ''
      @specification.groups << group
    end
    if @specification.save
      redirect_to group_specifications_path, notice: 'Specification was successfully created'
    else
      render 'new'
    end
  end

  private

  def specification_params
    params.require(:specification).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/specifications_helper.rb
module SpecificationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<%= stylesheet_link_tag 'groups/index', media: 'all' %>
<div class= 'category-cont'>
    <div class='category-header'>
        <h1 class='category-title'>Categories</h1>
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fas fa-sign-out-alt"></i>
        <% end %>
    </div>

<div class='categories-container'>
<% @categories.each do |categorie|%>
    <%= link_to group_specifications_path(categorie.id) do %>
    
    <div class='categorie-item'>
        <img src="<%=categorie.icon%>" alt="<%=categorie.name%>">
        <h2><%=categorie.name%></h2>
        <p>Total Spent: $<span><%=categorie.total_spent%></span></p>
    </div>

    <%end%>
<%end%>
</div>
<div class='btn-cont'><%= link_to new_group_path do %>
    <button class='categorie-add'>Add new Category</button>
<%end%>
</div>

app/views/groups/new.html.erb
<%= stylesheet_link_tag 'groups/index', media: 'all' %>

<div class= 'category-cont'>

<div class='category-header'>
<%=link_to groups_path do %>
    <i class="fas fa-arrow-left"></i>
<%end%>

<h1 class='category-title'>Add Category</h1>
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    <i class="fas fa-sign-out-alt"></i>
<% end %>
</div>

<div class='categories_container'>

<%= form_for @categorie, url: groups_path, method: :post do |f| %>
    <div class='categorie-body'>
        <div class='form-group'>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder:'Name', class:'form-inp' %>            
        </div>

        <div class='form-group'>
            <%= f.text_field :icon, autofocus: true, autocomplete: "icon", placeholder:'Icon', class:'form-inp' %>
        </div>
    </div>
<div class='btn-cont'>
    <%= f.submit 'Add Category', class:'btn-category' %>
</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/3ec9f83423.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/splash.html.erb
<%= stylesheet_link_tag 'pages/splash', media: 'all' %>

<div class='splash-cont'>

<h1 class='splash-title'>My Budget App</h1>

<div class='splash-btns'>
<%= link_to 'Login', new_user_session_path, class: 'splash-login' %>
<%= link_to 'Sign Up', new_user_registration_path, class: 'splash-signup' %>
</div>
</div>

app/views/specifications/index.html.erb
<%= stylesheet_link_tag 'specifications/index', media: 'all' %> 

<div class='spec-cont'>
    <div class='specification-header'>

        <%= link_to groups_path do %>
            <i class="fas fa-arrow-left"></i>
        <%end%>

        <h1 class='specification_title'>Specifications</h1>

        <%= link_to destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fas fa-sign-out-alt"></i>
        <% end %>

    </div>

    <div class='specifications-container'>
        <div class='specification-item'>
        <img src="<%= @group.icon %>" alt="<%= @group.name %>"> 
            <span>Category: <%= @group.name %></span>

        </div>

        <div class='specification-item'>

            <p>Total Amount: </p>
            <span>$<%= @group.total_spent %></span>

        </div>

        <table>
            <thead>
                <tr>
                    <th>Specification</th>
                    <th>Date</th>
                    <th>Name</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>

                <%if @specifications.empty? %>
                    <tr>
                    <td>
                        <img src="https://img.icons8.com/ios/50/000000/empty-box.png" alt="empty-box">
                    </td>
                        <td colspan='4'>No specifications yet</td>
                    </tr>
                <%end%>

                <%@specifications.each do |specification|%>
                <tr>
                    <td><img src= "https://img.icons8.com/ios/50/000000/checked-checkbox.png" alt="checked-checkbox"></td>
                    <td><%=specification.created_at.strftime("%d/%m/%Y")%></td>
                    <td><%=specification.name%></td>
                    <td>$<%=specification.amount %></td>
                </tr>
                <%end%>
            </tbody>
        </table>
    </div>

<div class='btn-cont'>
<%= link_to new_group_specification_path(@group.id) do %>
    <button class='spec-add'>Add new Specification</button>
<%end%>
</div>
</div>

app/views/specifications/new.html.erb
<%= stylesheet_link_tag 'specifications/new', media: 'all' %>

<div class= spec-cont>
    <div class='specification-header'>
        <%=link_to groups_path do %>
            <i class="fas fa-arrow-left"></i>
        <%end%>
        <h1 class='specification-title'>Specifications</h1>
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fas fa-sign-out-alt"></i>
        <% end %>
    </div>

<div class='specifications-container'>

<%= form_for @specification, url: group_specifications_path, method: :post do |f| %> 

    <div class='specification-item'>
        <div class='form-group'>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Name', class:'form-inp' %>            
        </div>

        <div class='form-group'>
            <%= f.text_field :amount, autofocus: true, autocomplete: "amount", placeholder: 'Amount', class:'form-inp' %>
        </div>
    
    <% if @groups.any? %>
        <div class='form-group'>
            <%= f.label :categories, class:'form-label' %> <br>
            <%= select_tag :groups, options_for_select(@groups.map{|g| [g.name, g.id]}), class:'form-category', multiple: true, size: 3 %>
        </div>
    <% end %>
 </div>
    
   


<div class='btn-cont'>
    <%= f.submit 'Add Category', class:'spec-add' %>
</div>
<% end %>
</div>
</div>